package e.s.miniweb.core.template;

import java.util.List;

import e.s.miniweb.core.PageInteractions;

/**
 * The path to a document template, and the model data to go in it, and some details for the hot-reload system.
 * This is all we need to render a final page.
 */
public class TemplateResponse {
    /** Model to use for rendering template */
    public Object Model;

    /** Path to HTML template */
    public String TemplatePath;

    /** If not null, the web view will be redirected to this url */
    public String RedirectUrl;

    /** if true AND RedirectUrl is set, the web view history will be cleared after rendering the page. */
    public boolean ShouldClearHistory = false;

    /** The page markup generated by template engine */
    public String ResponseBody;

    /** Controller or other interaction target to call if page calls "PageRequest()" */
    public PageInteractions CallbackTarget;

    // Internal
    public List<String> TemplateLines;

    // These are used to match a refresh to a hot-reload
    public String Controller;
    public String Method;
    public String Params;
    public String LastPageChangeDate;
}
